### ISSUE TITLE
does not have a member named 

### ISSUE THREAD

**Issue by wodetian** [QueryKit/QueryKit#25]
![a1654102-3410-4055-898d-b1db24c72d9e](https://cloud.githubusercontent.com/assets/6121524/6435328/f3bac95a-c0d6-11e4-8fe1-8ed4b6123afc.png)

I created a list of type when I get his and screening, tip me the news. How is this to return a responsibility excuse me

**Comment by kylef** [comment]
Hi @wodetian, you need to manually create these properties or use [mogenerator](https://github.com/QueryKit/mogenerator-template). I've updated the README to mention this a bit clearer.
