### ISSUE TITLE
Xcode 6.3 / Swift 1.2 support

### ISSUE THREAD

**Issue by robertjpayne** [QueryKit/QueryKit#26]
@kylef do you have plans to get the repo compatible with Xcode 6.3 / Swift 1.2? I've made some progress in a fork and it all seems straightforward except a few things with attributes.

**Comment by kylef** [comment]
I haven't yet moved to Xcode 6.3 so I never needed to make it work yet. But since there is *some* demand, I've created a PR (#27) and a branch `swift-1.2` which has most of the changes. It's just missing support for the `IN` and `BETWEEN` operators `<<`.

**Comment by robertjpayne** [comment]
@kylef thanks!

**Comment by wodetian** [comment]
hello,Are you going to do with something about "Relationships"?

**Comment by kylef** [comment]
@wodetian What about relationships? Can you file a new issue, this doesn't seem related to Swift 1.2 support.

**Comment by wodetian** [comment]
There is nothing... Just think coredata since there is this thing, should be useful, although I do not know what use is he... ,😓😓

**Comment by kylef** [comment]
@wodetian I have absolutely no idea what you are talking about, can you add a little bit more information about what your problem is?

**Comment by wodetian** [comment]
😂😂😂😂  giveu up

**Comment by Speedrockracer** [comment]
Is this still being updated? By now apple pushes swift 1.2 so would be nice but I can't get the branch to work for iOS.

**Comment by kylef** [comment]
@Speedrockracer, the Swift branch works. I'll try merge it soon

**Comment by Speedrockracer** [comment]
Thanks mate. I Did something wrong but its working now! Would be nice if you merged it so the cocoapod wil work.

**Comment by kylef** [comment]
This is out in 0.10.0 now.
