### ISSUE TITLE
unsafeBitCast results in a EXC_BAD_INSTRUCTION on non 64 Bit device

### ISSUE THREAD

**Issue by dirkfabisch** [QueryKit/QueryKit#29]
When I execute my QueryKit app on a non 64 bit device I get a EXC_BAD_INSTRUCTION at following code sample:

    var qs = Sensor.queryset(managedObjectContext).filter(
        Sensor.attributes.sensorStarted != 0 &&
        Sensor.attributes.sensorStopped == 0)

In the QueryKit source code attributes.swift in line 50

            let value = unsafeBitCast(value, Optional<NSObject>.self)

I get this error: `fatal error: can't unsafeBitCast between types of different sizes`
Everything works as expected on 64 bit devices.

**Comment by kylef** [comment]
Thanks for reporting @dirkfabisch. Sorry about this, will find a fix and release an update shortly.

Also to prevent these kind of bugs happening again in the future, I will configure travis (our CI system) to run the unit tests against 32-bit devices too so we catch them earlier.

**Comment by kylef** [comment]
@dirkfabisch QueryKit 0.9.2 is out and fixes this problem.

**Comment by dirkfabisch** [comment]
That was fast! Great Work! No more EXC_BAD. Thanks!
