### ISSUE TITLE
About mogenerator template 

### ISSUE THREAD

**Issue by wodetian** [QueryKit/QueryKit#34]
Upgrade 1.2, isn't it under response should upgrade mogenerator template ，

About the as is added behind! The problem of 。。

🙈🙈🙈🙈

**Comment by iodos** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

mylaboratory@naver.com 님께 보내신 메일 <Re: [QueryKit] About mogenerator template (#34)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by wodetian** [comment]
when one To Many  mogenerator template is Wrong。

**Comment by kylef** [comment]
See http://github.com/QueryKit/querykit-cli.
