### ISSUE TITLE
hello.What reason is this excuse me 

### ISSUE THREAD

**Issue by wodetian** [QueryKit/QueryKit#35]
````
   struct Attributes {
        var commGround:Attribute<String?> {
            return Attribute<String?>("commGround")
        }
        var createDateTime:Attribute<NSDate?> {
            return Attribute<NSDate?>("createDateTime")
        }
        var gender:Attribute<String?> {
            return Attribute<String?>("gender")
        }
        var headPhotoKey:Attribute<String?> {
            return Attribute<String?>("headPhotoKey")
        }
        var id:Attribute<String?> {
            return Attribute<String?>("id")
        }
        var name:Attribute<String?> {
            return Attribute<String?>("name")
        }
        var signature:Attribute<String?> {
            return Attribute<String?>("signature")
        }
        var sinaId:Attribute<String?> {
            return Attribute<String?>("sinaId")
        }
        var userBacks:Attribute<CoreDataUserBack?> {
            return Attribute<CoreDataUserBack?>("userBacks")
        }
        var userLabels:Attribute<CoreDataUserLabel?> {
            return Attribute<CoreDataUserLabel?>("userLabels")
        }
    }
```


I used your ` mogenerator template `,but When I use the provided by you 
`queryset.filter(Person.attributes.name == "Kyle")`
It went wrong 
`Binary operator '==' cannot be applied to operands of type 'Attribute<String?>' and 'String'`

this is myCode 
````
        var quset = CoreDataUser.queryset(currageContext)
        
        quset.filter(CoreDataUser.attributes.id == "Kyle")
```
Can you point out my mistakes, or repair it ?

**Comment by iodos** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

mylaboratory@naver.com 님께 보내신 메일 <[QueryKit] hello.What reason is this excuse me (#35)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by phimage** [comment]
your attribute `name` is optional (`String?`)
`"Kyle"` is not
`==` operator is provided for : `Attribute<T>,T`  (`T` could be `String` or `String?`)

I add an operator in my source code to achieve == with optional
```swift
public func == <AttributeType>(left: Attribute<AttributeType?>, right: AttributeType) -> NSPredicate {
    var rightOptional: AttributeType? = right
    return left == rightOptional
}
```

**Comment by iodos** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

mylaboratory@naver.com 님께 보내신 메일 <Re: [QueryKit] hello.What reason is this excuse me (#35)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by wodetian** [comment]
Thank you very much,
I'd like to try, but I now have to upgrade to the `swift2.0`, unfortunately. Wait until `QueryKit` also updated to 2.0.

**Comment by kylef** [comment]
@wodetian I've implemented a brand new tool for Swift 2.0, check it out at http://github.com/QueryKit/querykit-cli.
