### ISSUE TITLE
Swift 2.0 Support

### ISSUE THREAD

**Issue by dirkfabisch** [QueryKit/QueryKit#36]
Hi,

when do you plan to support Swift 2.0

.dirk

**Comment by iodos** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

mylaboratory@naver.com 님께 보내신 메일 <[QueryKit] Swift 2.0 Support (#36)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by kylef** [comment]
I've created a swift-2.0 branch, and there is a pull request at https://github.com/QueryKit/QueryKit/pull/37.

**Comment by iodos** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

mylaboratory@naver.com 님께 보내신 메일 <Re: [QueryKit] Swift 2.0 Support (#36)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------
