### ISSUE TITLE
Framework doesn't build using Carthage

### ISSUE THREAD

**Issue by alessandroorru** [QueryKit/QueryKit#42]
There are currently issues using this framework with Carthage (i'm using 0.9.2, latest version):

Here is the output of `carthage build --verbose`:

```
Build settings from command line:
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = watchsimulator2.0

=== BUILD TARGET QueryKit OF PROJECT QueryKit WITH CONFIGURATION Release ===

Check dependencies
No architectures to compile for (ARCHS=x86_64, VALID_ARCHS=armv7k).
```

I get the same output even using `--platform iOS` flag to force compilation only for iOS.

**Comment by kylef** [comment]
Hi @alessandroorru, I'm not able to get Carthage 0.9.2 installed (Homebrew only has 0.8 and the .pkg hangs on "Verifying..." (left it for 20 minutes).

![screen shot 2015-10-06 at 08 37 03](https://cloud.githubusercontent.com/assets/44164/10313624/78a13cf6-6c05-11e5-856d-23a26105d157.png)

As for the problem, using xcodebuild directly for both watchOS and iOS succeeds:

```shell
$ xcodebuild -project QueryKit.xcodeproj -scheme QueryKit build -sdk watchos
Build settings from command line:
    SDKROOT = watchos2.0

=== BUILD TARGET QueryKit OF PROJECT QueryKit WITH CONFIGURATION Debug ===

Check dependencies

** BUILD SUCCEEDED **
```

```shell
$ xcodebuild -project QueryKit.xcodeproj -scheme QueryKit build -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
Build settings from command line:
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = iphonesimulator9.0

=== BUILD TARGET QueryKit OF PROJECT QueryKit WITH CONFIGURATION Debug ===

Check dependencies

** BUILD SUCCEEDED **
```

Which leaves my to believe this is a Carthage problem (unless you can point me out as to what QueryKit is doing wrong).

**Comment by alessandroorru** [comment]
Hi @kylef  ! 

You tried with the wrong command.. it fails on watch simulator, not iphone one ;)

```
❱ xcodebuild -project QueryKit.xcodeproj -scheme QueryKit build -sdk watchsimulator ONLY_ACTIVE_ARCH=NO          

Build settings from command line:
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = watchsimulator2.0

=== BUILD TARGET QueryKit OF PROJECT QueryKit WITH CONFIGURATION Debug ===

Check dependencies
No architectures to compile for (ARCHS=x86_64, VALID_ARCHS=armv7k).

** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
```

**Comment by kylef** [comment]
Okay thanks @alessandroorru, just looking into this should  have it working soon.
