### ISSUE TITLE
Conforming to `CollectionType`

### ISSUE THREAD

**Issue by LeeroyDing** [QueryKit/QueryKit#49]
I find myself extending `QuerySet` to conform to `CollectionType` so that I can write my models in a more protocol-oriented way. I wonder if there's any concern not to do this. If there's none I'll send my PR.

**Comment by kylef** [comment]
@LeeroyDing Wouldn't that make it impossible to handle errors?

You could easily turn a query into an array which is `CollectionType`, for example:

```
do {
  try queryset.array()
} catch {
  print("there was an error \(error)")
}
```

**Comment by kylef** [comment]
Closing due to lack of response.
