### ISSUE TITLE
Have you consider to make NSPredicate extensions with Attribute<T> independent library ?

### ISSUE THREAD

**Issue by sergdort** [QueryKit/QueryKit#50]
Hi, first of all thank you very much for such a cool library!

Please correct me if I'm wrong, but to me looks like that some features of this library dependent on CoreData and some are not (e.g `NSPredicate` extensions)

So I was thinking is it possible to use some of that features without `CoreData` (e.g `Realm`, because It's also possible to fetch objects from DB using `NSPredicate`) ?

If it possible, do you think it would make sense to make additional library for this so `QueryKit` will be dependent on that lib, but other users (e.g like Realm users) will use that library instead for `NSPredicate` sugar?

**Comment by kylef** [comment]
@jpsim was exploring this while he worked at Realm apart of the Swift syntax.

- https://github.com/realm/realm-cocoa/pull/889#issuecomment-55203367
- https://github.com/realm/realm-cocoa/pull/889#issuecomment-67054368

I'm not sure what happened to his efforts and if anything ever came of this. But I do recall speaking with @jpsim about just this. There was at some point some interest in adding similar functionality to Realm.

I personally do not use Realm so these efforts will need to be lead by a volunteer. I think we can do this and if you're interested I'm happy to create a `QueryKitReam` or similar repo in the organisation so you can add the necessary Realm specific extensions and we can work together to make CoreData optional from QueryKit base.

**Comment by kylef** [comment]
Looks like https://github.com/kishikawakatsumi/RealmTypeSafeQuery provides better behaviour leveraging Swift 4 and I don't think we need to do this in QueryKit.
